def tools():
    print("<--------------------------------------------------------------------------------------------------------------->")
    print("|                                              CROCHET TOOLS                                                    |")
    print("<--------------------------------------------------------------------------------------------------------------->")
    print("| Hook                                                                                                          |")
    print("| - A slender tool, typically made of metal, plastic, or wood, with a hooked end used to pull loops of yarn     |")
    print("|   through other loops to create stitches.                                                                     |")
    print("| - It comes in various sizes, each designed for different yarn sizes.                                          |")
    print("|\n Stitch Markers                                                                                              |")
    print("| - Small, often colorful, plastic clips or metal rings used to mark specific points in a crochet project.      |")
    print("|   crochet project.                                                                                            |")
    print("| - They help in tracking the beginning or ending of rounds, marking increases or decreases, or indicating a    |")
    print("|   particular stitch pattern.                                                                                  |")
    print("|\n Darning Needle                                                                                              |")
    print("| - A large, blunt needle with an elongated eye, used for sewing yarn ends into finished crochet projects.      |")
    print("| - It's essential for weaving in loose ends to give the project a polished look.                               |")
    print("|\n Bent Tip Needle                                                                                             |")
    print("| - Similiar to a darning needle but with a bent tip, making it easier to weae through tight or dense stitches. |")
    print("| - This needle is particularly useful for finishing intricate crochet projects.                                |")
    print("|\n Tape Measure                                                                                                |")
    print("| - A flexible, retractable measuring tool used to ensure that crochet projects meet specific dimensions.       |")
    print("| - It helps in checking gauge, measuring lengths, and ensuring the correct size of finished items.             |")
    print("|\n Crafting Scissor                                                                                            |")
    print("| - Small, sharpe scissor designed for cutting yarn and thread.                                                 |")
    print("| - They often have pointed tips for precise snipping and are an essential tool for trimming loose ends in      |")
    print("|   crochet projects.                                                                                           |")
    print("|\n Yarn Ball Winder                                                                                            |")
    print("| - A mechanical device used to wind yarn into a neat, compact ball or 'cake' shape.                            |")
    print("| - It helps in preventing tangles and makes it easier to work with the yarn, allowing for smoother stitching.  |")
    print("<--------------------------------------------------------------------------------------------------------------->")