def yarns():
    print("<--------------------------------------------------------------------------------------------------------------->")
    print("|                                           YARN DESCRIPTIONS                                                   |")
    print("<--------------------------------------------------------------------------------------------------------------->")
    print("| Cotton Yarn                                                                                                   |")
    print("| - Is made from natural cotton fibers and is known for its softness, breathability, and durability.            |")
    print("| - It has a smooth texture, making it ideal for projects that require stitch definition.                       |")
    print("|\n Indophil Yarn                                                                                               |")
    print("| - Is a blend of cotton and polyester, offering the best both worlds.                                          |")
    print("| - The cotton provides softness and breathability, while the polyester adds strength, durability, and a slight |")
    print("|   sheen.                                                                                                      |")
    print("|\n Polyester Yarn                                                                                              |")
    print("| - Is a synthetic fiber known for its durability, elasticity, and resistant to moisture and mildew.            |")
    print("| - It has a smooth, sometimes slightly shiny texture and is often used for projects that require a strong,     |")
    print("|   long-lasting yarn, such as blankets, bags, and outdoor items.                                               |")
    print("|\n Acrylic Yarn                                                                                                |")
    print("| - Is a popular synthetic option, known for its affordability, versatility, and wide range of colors.          |")
    print("| - It's lightweight, warm, and easy to care for, making it ideal for beginners and a variety of projects.      |")
    print("|\n Velvet Yarn                                                                                                 |")
    print("| - Is luxuriously soft and plush, with a velvety texture that adds a rich, tactile quality to projects.        |")
    print("| - Made from synthetic fibers like polyester or acrylic.                                                       |")
    print("|\n Vhunky Yarn                                                                                                 |")
    print("| - Is a thick, bulky yarn that works up quickly, and creates a thick fabric with excellent stitch definition,  |")
    print("|   adding texture and visual interest to any project.                                                          |")
    print("<--------------------------------------------------------------------------------------------------------------->")